services:
  postgres:
    image: postgres:17
    container_name: kharjam-split-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - split-network
      - rabbitmq-network
      - redis-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  split-service:
    build: 
      context: .
    image: kharjam/split-service:v1.0.0
    container_name: kharjam-split-service
    ports:
      - "8003:8000"
    env_file:
      - .env
    environment:
      PYTHONUNBUFFERED: "1"
    volumes:
      - ./app/db:/split_service/app/db
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - split-network
      - rabbitmq-network
      - redis-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  postgres_data:

networks:
  split-network:
    driver: bridge
  rabbitmq-network:
    external: true
    name: rabbitmq_rabbitmq-network
  redis-network:
    external: true
    name: redis_network
